zservices:
  app:
    image: httpd
    ports:
      - 9000:80
    working_dir: /usr/local/apache2/htdocs/
    volumes:
      - type: bind
        source: ./app
        target: /usr/local/apache2/htdocs/
      - type: bind
        source: <CLIENT_VIDEO_ROOT>
        target: /usr/local/apache2/htdocs/Videos/
    environment:
      - ACCESS_KEY=<SITE_ACCESS_KEY>
      - VIDEO_ROOT=<SERVER_VIDEO_ROOT>