version: "3.9"

services:
  web-service:
    image: php:8.0-apache
    ports:
      - 80:80
    working_dir: /var/www/html
    volumes:
      - type: bind
        source: ./app
        target: /var/www/html
      - type: bind
        source: <MOUNTED_VIDEO_ROOT
        target: /var/www/html/Videos